--------------------------------------------------------
--  파일이 생성됨 - 목요일-6월-14-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIP_ACTION_GROUP_AUTH
--------------------------------------------------------

  CREATE TABLE "CLIPSOFT"."CLIP_ACTION_GROUP_AUTH" 
   (	"PRODUCT_ID" NUMBER, 
	"USER_GROUP_ID" VARCHAR2(100 BYTE),    
	"ACTION_CODE" VARCHAR2(100 BYTE), 
	"AUTH_CODE" VARCHAR2(50 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_ID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Table CLIP_ACTION_USER_AUTH
--------------------------------------------------------

  CREATE TABLE "CLIPSOFT"."CLIP_ACTION_USER_AUTH" 
   (	"PRODUCT_ID" NUMBER, 
	"USER_ID" VARCHAR2(100 BYTE), 
	"ACTION_CODE" VARCHAR2(100 BYTE), 
	"AUTH_CODE" VARCHAR2(50 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_ID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Table CLIP_CODE
--------------------------------------------------------

  CREATE TABLE "CLIPSOFT"."CLIP_CODE" 
   (	"PRODUCT_ID" NUMBER, 
	"CODE" VARCHAR2(50 BYTE), 
	"CODE_DIV" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"SEQ" NUMBER, 
	"CREATE_DATE" DATE, 
	"CREATE_USER_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_ID" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Table CLIP_FORM
--------------------------------------------------------

  CREATE TABLE "CLIPSOFT"."CLIP_FORM" 
   (	"PRODUCT_ID" NUMBER, 
	"FORM_ID" NUMBER, 
	"FORM_TYPE" VARCHAR2(50 BYTE), 
	"FORM_NAME" VARCHAR2(500 BYTE), 
	"USE_YN" VARCHAR2(1 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_ID" VARCHAR2(100 BYTE), 
	"FORM_CATEGORY_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Table CLIP_FORM_CATEGORY
--------------------------------------------------------

  CREATE TABLE "CLIPSOFT"."CLIP_FORM_CATEGORY" 
   ( "PRODUCT_ID" NUMBER DEFAULT NULL,	
   "FORM_CATEGORY_ID" NUMBER, 
   	"FORM_CATEGORY_CODE" VARCHAR(100),
	"PARENT_FORM_CATEGORY_ID" NUMBER, 
	"FORM_CATEGORY_NAME" VARCHAR2(100 BYTE), 
	"SEQ" NUMBER, 
	"USE_YN" VARCHAR2(2 BYTE),
	"CREATE_DATE" DATE, 
	"CREATE_USER_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_ID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Table CLIP_FORM_CATEGORY_GROUP_AUTH
--------------------------------------------------------

  CREATE TABLE "CLIPSOFT"."CLIP_FORM_CATEGORY_GROUP_AUTH" 
   (	"USER_GROUP_ID" VARCHAR2(100 BYTE), 
	"FORM_CATEGORY_ID" NUMBER, 
	"AUTH_CODE" VARCHAR2(50 BYTE),
	"CREATE_DATE" DATE, 
	"CREATE_USER_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_ID" VARCHAR2(100 BYTE), 
	"PRODUCT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Table CLIP_FORM_CATEGORY_USER_AUTH
--------------------------------------------------------

  CREATE TABLE "CLIPSOFT"."CLIP_FORM_CATEGORY_USER_AUTH" 
   (	"USER_ID" VARCHAR2(100 BYTE), 
	"FORM_CATEGORY_ID" NUMBER, 
	"AUTH_CODE" VARCHAR2(50 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_ID" VARCHAR2(100 BYTE), 
	"PRODUCT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Table CLIP_FORM_DATA
--------------------------------------------------------

  CREATE TABLE "CLIPSOFT"."CLIP_FORM_DATA" 
   (	"PRODUCT_ID" NUMBER, 
	"FORM_ID" NUMBER, 
	"FORM_VERSION" NUMBER, 
	"FORM_DATA" BLOB, 
	"COMMIT_COMMENT" VARCHAR2(1000 BYTE), 
	"PUBLICATION_YN" VARCHAR2(1 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_ID" VARCHAR2(100 BYTE), 
	"ENCRYPTION_YN" VARCHAR2(1 BYTE), 
	"COMPRESSION_YN" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" 
 LOB ("FORM_DATA") STORE AS BASICFILE (
  TABLESPACE "CLIP_REPOSITORY_SERVER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CLIP_FORM_USER_AUTH
--------------------------------------------------------

  CREATE TABLE "CLIPSOFT"."CLIP_FORM_USER_AUTH" 
   (	"USER_ID" VARCHAR2(100 BYTE), 
	"FORM_ID" NUMBER, 
	"AUTH_CODE" VARCHAR2(50 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_ID" VARCHAR2(100 BYTE), 
	"PRODUCT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Table CLIP_FORM_USER_GROUP_AUTH
--------------------------------------------------------

  CREATE TABLE "CLIPSOFT"."CLIP_FORM_USER_GROUP_AUTH" 
   (	"USER_GROUP_ID" VARCHAR2(100 BYTE), 
	"FORM_ID" NUMBER, 
	"AUTH_CODE" VARCHAR2(50 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_ID" VARCHAR2(100 BYTE), 
	"PRODUCT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Table CLIP_MANAGE_ID
--------------------------------------------------------

  CREATE TABLE "CLIPSOFT"."CLIP_MANAGE_ID" 
   (	"KEY" VARCHAR2(100 BYTE), 
	"VALUE" NUMBER, 
	"CREATE_DATE" DATE, 
	"CREATE_USER_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_ID" VARCHAR2(100 BYTE), 
	"PRODUCT_ID" NUMBER DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Table CLIP_PRODUCT
--------------------------------------------------------

  CREATE TABLE "CLIPSOFT"."CLIP_PRODUCT" 
   (	"PRODUCT_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_ID" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Table CLIP_USER
--------------------------------------------------------

  CREATE TABLE "CLIPSOFT"."CLIP_USER" 
   (	"USER_ID" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"USE_YN" VARCHAR2(1 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_ID" VARCHAR2(100 BYTE), 
	"PRODUCT_ID" NUMBER DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Table CLIP_USER_GROUP
--------------------------------------------------------

  CREATE TABLE "CLIPSOFT"."CLIP_USER_GROUP" 
   (	"USER_GROUP_ID" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_ID" VARCHAR2(100 BYTE), 
	"PRODUCT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Table CLIP_USER_GROUP_MAPPING
--------------------------------------------------------

  CREATE TABLE "CLIPSOFT"."CLIP_USER_GROUP_MAPPING" 
   (	"USER_ID" VARCHAR2(100 BYTE), 
	"USER_GROUP_ID" VARCHAR2(100 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_ID" VARCHAR2(100 BYTE), 
	"PRODUCT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
REM INSERTING into CLIPSOFT.CLIP_CODE
SET DEFINE OFF;
Insert into CLIPSOFT.CLIP_CODE (PRODUCT_ID,CODE,CODE_DIV,NAME,SEQ,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,DESCRIPTION) values (1,'FORM_TYPE_001','FORM_TYPE','서식',1,to_date('18/05/14','RR/MM/DD'),'admin',to_date('18/05/14','RR/MM/DD'),'admin',null);
Insert into CLIPSOFT.CLIP_CODE (PRODUCT_ID,CODE,CODE_DIV,NAME,SEQ,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,DESCRIPTION) values (1,'FORM_TYPE_002','FORM_TYPE','외부 사용자 정의 컨트롤',2,to_date('18/05/14','RR/MM/DD'),'admin',to_date('18/05/14','RR/MM/DD'),'admin',null);
Insert into CLIPSOFT.CLIP_CODE (PRODUCT_ID,CODE,CODE_DIV,NAME,SEQ,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,DESCRIPTION) values (1,'FORM_TYPE_003','FORM_TYPE','페이지 템플릿',3,to_date('18/05/14','RR/MM/DD'),'admin',to_date('18/05/14','RR/MM/DD'),'admin',null);
Insert into CLIPSOFT.CLIP_CODE (PRODUCT_ID,CODE,CODE_DIV,NAME,SEQ,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,DESCRIPTION) values (1,'FORM_TYPE_004','FORM_TYPE','사용자 다이얼로그',4,to_date('18/05/14','RR/MM/DD'),'admin',to_date('18/05/14','RR/MM/DD'),'admin',null);
Insert into CLIPSOFT.CLIP_CODE (PRODUCT_ID,CODE,CODE_DIV,NAME,SEQ,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,DESCRIPTION) values (1,'ACTION_001','ACTION','외부 사용자 정의 컨트롤',1,to_date('18/05/25','RR/MM/DD'),'admin',to_date('18/05/25','RR/MM/DD'),'admin',null);
Insert into CLIPSOFT.CLIP_CODE (PRODUCT_ID,CODE,CODE_DIV,NAME,SEQ,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,DESCRIPTION) values (1,'ACTION_AUTH_001','ACTION_AUTH','등록',1,to_date('18/05/25','RR/MM/DD'),'admin',to_date('18/05/25','RR/MM/DD'),'admin',null);
Insert into CLIPSOFT.CLIP_CODE (PRODUCT_ID,CODE,CODE_DIV,NAME,SEQ,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,DESCRIPTION) values (1,'ACTION_002','ACTION','페이지 템플릿',2,to_date('18/05/25','RR/MM/DD'),'admin',to_date('18/05/25','RR/MM/DD'),'admin',null);
Insert into CLIPSOFT.CLIP_CODE (PRODUCT_ID,CODE,CODE_DIV,NAME,SEQ,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,DESCRIPTION) values (1,'FORM_AUTH_001','FORM_AUTH','조회',1,to_date('18/05/21','RR/MM/DD'),'admin',to_date('18/05/21','RR/MM/DD'),'admin','디자이너 상에서 서식 목록(Tree)에서 조회 할 수 있는 권한');
Insert into CLIPSOFT.CLIP_CODE (PRODUCT_ID,CODE,CODE_DIV,NAME,SEQ,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,DESCRIPTION) values (1,'FORM_AUTH_002','FORM_AUTH','수정',2,to_date('18/05/21','RR/MM/DD'),'admin',to_date('18/05/21','RR/MM/DD'),'admin','기 등록된 서식의 수정(사용중지 포함)을 할 수 있는 권한');
Insert into CLIPSOFT.CLIP_CODE (PRODUCT_ID,CODE,CODE_DIV,NAME,SEQ,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,DESCRIPTION) values (1,'FORM_AUTH_004','FORM_AUTH','삭제',5,to_date('18/05/21','RR/MM/DD'),'admin',to_date('18/05/21','RR/MM/DD'),'admin',null);
Insert into CLIPSOFT.CLIP_CODE (PRODUCT_ID,CODE,CODE_DIV,NAME,SEQ,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,DESCRIPTION) values (1,'CATEGORY_AUTH_001','CATEGORY_AUTH','조회',1,to_date('18/05/21','RR/MM/DD'),'admin',to_date('18/05/21','RR/MM/DD'),'admin','해당 분류를 볼 수 있는 권한');
Insert into CLIPSOFT.CLIP_CODE (PRODUCT_ID,CODE,CODE_DIV,NAME,SEQ,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,DESCRIPTION) values (1,'CATEGORY_AUTH_002','CATEGORY_AUTH','수정',2,to_date('18/05/21','RR/MM/DD'),'admin',to_date('18/05/21','RR/MM/DD'),'admin','기 등록된 분류의 수정(사용중지 포함)을 할 수 있는 권한');
Insert into CLIPSOFT.CLIP_CODE (PRODUCT_ID,CODE,CODE_DIV,NAME,SEQ,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,DESCRIPTION) values (1,'CATEGORY_AUTH_003','CATEGORY_AUTH','서식생성',3,to_date('18/05/21','RR/MM/DD'),'admin',to_date('18/05/21','RR/MM/DD'),'admin','해당 분류에 서식을 생성 할 수 있는 권한');
Insert into CLIPSOFT.CLIP_CODE (PRODUCT_ID,CODE,CODE_DIV,NAME,SEQ,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,DESCRIPTION) values (1,'CATEGORY_AUTH_004','CATEGORY_AUTH','분류생성',4,to_date('18/05/21','RR/MM/DD'),'admin',to_date('18/05/21','RR/MM/DD'),'admin','해당 분류 하위에 또다른 분류를 생성 할 수 있는 권한');
Insert into CLIPSOFT.CLIP_CODE (PRODUCT_ID,CODE,CODE_DIV,NAME,SEQ,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,DESCRIPTION) values (1,'CATEGORY_AUTH_005','CATEGORY_AUTH','삭제',5,to_date('18/05/21','RR/MM/DD'),'admin',to_date('18/05/21','RR/MM/DD'),'admin',null);
Insert into CLIPSOFT.CLIP_CODE (PRODUCT_ID,CODE,CODE_DIV,NAME,SEQ,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,DESCRIPTION) values (1,'FORM_AUTH_003','FORM_AUTH','게시',3,to_date('18/05/21','RR/MM/DD'),'admin',to_date('18/05/21','RR/MM/DD'),'admin',null);
REM INSERTING into CLIPSOFT.CLIP_MANAGE_ID
SET DEFINE OFF;
Insert into CLIPSOFT.CLIP_MANAGE_ID (KEY,VALUE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,PRODUCT_ID) values ('PRODUCT_ID',1,to_date('18/05/14','RR/MM/DD'),'admin',to_date('18/05/14','RR/MM/DD'),'admin',1);
Insert into CLIPSOFT.CLIP_MANAGE_ID (KEY,VALUE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,PRODUCT_ID) values ('FORM_ID',1,to_date('18/05/14','RR/MM/DD'),'admin',to_date('18/05/14','RR/MM/DD'),'admin',1);
Insert into CLIPSOFT.CLIP_MANAGE_ID (KEY,VALUE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,PRODUCT_ID) values ('FORM_CATEGORY_ID',1,to_date('18/05/20','RR/MM/DD'),'admin',to_date('18/05/20','RR/MM/DD'),'admin',1);
--------------------------------------------------------
--  DDL for Index CLIP_ACTION_GROUP_AUTH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIPSOFT"."CLIP_ACTION_GROUP_AUTH_PK" ON "CLIPSOFT"."CLIP_ACTION_GROUP_AUTH" ("PRODUCT_ID", "USER_GROUP_ID", "ACTION_CODE", "AUTH_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Index CLIP_ACTION_USER_AUTH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIPSOFT"."CLIP_ACTION_USER_AUTH_PK" ON "CLIPSOFT"."CLIP_ACTION_USER_AUTH" ("PRODUCT_ID", "USER_ID", "ACTION_CODE", "AUTH_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Index CLIP_CODE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIPSOFT"."CLIP_CODE_PK" ON "CLIPSOFT"."CLIP_CODE" ("PRODUCT_ID", "CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Index CLIP_FORM_CATEGORY_GROUP_A_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIPSOFT"."CLIP_FORM_CATEGORY_GROUP_A_PK" ON "CLIPSOFT"."CLIP_FORM_CATEGORY_GROUP_AUTH" ("USER_GROUP_ID", "FORM_CATEGORY_ID", "AUTH_CODE", "PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Index CLIP_FORM_CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIPSOFT"."CLIP_FORM_CATEGORY_PK" ON "CLIPSOFT"."CLIP_FORM_CATEGORY" ("FORM_CATEGORY_ID", "PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Index CLIP_FORM_CATEGORY_USER_AU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIPSOFT"."CLIP_FORM_CATEGORY_USER_AU_PK" ON "CLIPSOFT"."CLIP_FORM_CATEGORY_USER_AUTH" ("USER_ID", "FORM_CATEGORY_ID", "AUTH_CODE", "PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Index CLIP_FORM_DATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIPSOFT"."CLIP_FORM_DATA_PK" ON "CLIPSOFT"."CLIP_FORM_DATA" ("PRODUCT_ID", "FORM_ID", "FORM_VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Index CLIP_FORM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIPSOFT"."CLIP_FORM_PK" ON "CLIPSOFT"."CLIP_FORM" ("PRODUCT_ID", "FORM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Index CLIP_FORM_USER_AUTH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIPSOFT"."CLIP_FORM_USER_AUTH_PK" ON "CLIPSOFT"."CLIP_FORM_USER_AUTH" ("USER_ID", "FORM_ID", "AUTH_CODE", "PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Index CLIP_FORM_USER_GROUP_AUTH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIPSOFT"."CLIP_FORM_USER_GROUP_AUTH_PK" ON "CLIPSOFT"."CLIP_FORM_USER_GROUP_AUTH" ("USER_GROUP_ID", "FORM_ID", "AUTH_CODE", "PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Index CLIP_MANAGE_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIPSOFT"."CLIP_MANAGE_ID_PK" ON "CLIPSOFT"."CLIP_MANAGE_ID" ("KEY", "PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Index CLIP_PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIPSOFT"."CLIP_PRODUCT_PK" ON "CLIPSOFT"."CLIP_PRODUCT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Index CLIP_USER_GROUP_MAPPING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIPSOFT"."CLIP_USER_GROUP_MAPPING_PK" ON "CLIPSOFT"."CLIP_USER_GROUP_MAPPING" ("USER_ID", "USER_GROUP_ID", "PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Index CLIP_USER_GROUP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIPSOFT"."CLIP_USER_GROUP_PK" ON "CLIPSOFT"."CLIP_USER_GROUP" ("USER_GROUP_ID", "PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  DDL for Index CLIP_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIPSOFT"."CLIP_USER_PK" ON "CLIPSOFT"."CLIP_USER" ("USER_ID", "PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER" ;
--------------------------------------------------------
--  Constraints for Table CLIP_ACTION_GROUP_AUTH
--------------------------------------------------------

  ALTER TABLE "CLIPSOFT"."CLIP_ACTION_GROUP_AUTH" ADD CONSTRAINT "CLIP_ACTION_GROUP_AUTH_PK" PRIMARY KEY ("PRODUCT_ID", "USER_GROUP_ID", "ACTION_CODE", "AUTH_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER"  ENABLE;
  ALTER TABLE "CLIPSOFT"."CLIP_ACTION_GROUP_AUTH" MODIFY ("AUTH_CODE" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_ACTION_GROUP_AUTH" MODIFY ("ACTION_CODE" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_ACTION_GROUP_AUTH" MODIFY ("USER_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_ACTION_GROUP_AUTH" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIP_ACTION_USER_AUTH
--------------------------------------------------------

  ALTER TABLE "CLIPSOFT"."CLIP_ACTION_USER_AUTH" ADD CONSTRAINT "CLIP_ACTION_USER_AUTH_PK" PRIMARY KEY ("PRODUCT_ID", "USER_ID", "ACTION_CODE", "AUTH_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER"  ENABLE;
  ALTER TABLE "CLIPSOFT"."CLIP_ACTION_USER_AUTH" MODIFY ("AUTH_CODE" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_ACTION_USER_AUTH" MODIFY ("ACTION_CODE" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_ACTION_USER_AUTH" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_ACTION_USER_AUTH" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIP_CODE
--------------------------------------------------------

  ALTER TABLE "CLIPSOFT"."CLIP_CODE" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_CODE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_CODE" ADD CONSTRAINT "CLIP_CODE_PK" PRIMARY KEY ("PRODUCT_ID", "CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIP_FORM
--------------------------------------------------------

  ALTER TABLE "CLIPSOFT"."CLIP_FORM" ADD CONSTRAINT "CLIP_FORM_PK" PRIMARY KEY ("PRODUCT_ID", "FORM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER"  ENABLE;
  ALTER TABLE "CLIPSOFT"."CLIP_FORM" MODIFY ("FORM_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_FORM" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIP_FORM_CATEGORY
--------------------------------------------------------

  ALTER TABLE "CLIPSOFT"."CLIP_FORM_CATEGORY" MODIFY ("FORM_CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_CATEGORY" ADD CONSTRAINT "CLIP_FORM_CATEGORY_PK" PRIMARY KEY ("FORM_CATEGORY_ID", "PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER"  ENABLE;
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_CATEGORY" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIP_FORM_CATEGORY_GROUP_AUTH
--------------------------------------------------------

  ALTER TABLE "CLIPSOFT"."CLIP_FORM_CATEGORY_GROUP_AUTH" ADD CONSTRAINT "CLIP_FORM_CATEGORY_GROUP_A_PK" PRIMARY KEY ("USER_GROUP_ID", "FORM_CATEGORY_ID", "AUTH_CODE", "PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER"  ENABLE;
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_CATEGORY_GROUP_AUTH" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_CATEGORY_GROUP_AUTH" MODIFY ("AUTH_CODE" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_CATEGORY_GROUP_AUTH" MODIFY ("FORM_CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_CATEGORY_GROUP_AUTH" MODIFY ("USER_GROUP_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIP_FORM_CATEGORY_USER_AUTH
--------------------------------------------------------

  ALTER TABLE "CLIPSOFT"."CLIP_FORM_CATEGORY_USER_AUTH" ADD CONSTRAINT "CLIP_FORM_CATEGORY_USER_AU_PK" PRIMARY KEY ("USER_ID", "FORM_CATEGORY_ID", "AUTH_CODE", "PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER"  ENABLE;
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_CATEGORY_USER_AUTH" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_CATEGORY_USER_AUTH" MODIFY ("AUTH_CODE" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_CATEGORY_USER_AUTH" MODIFY ("FORM_CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_CATEGORY_USER_AUTH" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIP_FORM_DATA
--------------------------------------------------------

  ALTER TABLE "CLIPSOFT"."CLIP_FORM_DATA" ADD CONSTRAINT "CLIP_FORM_DATA_PK" PRIMARY KEY ("PRODUCT_ID", "FORM_ID", "FORM_VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER"  ENABLE;
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_DATA" MODIFY ("FORM_VERSION" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_DATA" MODIFY ("FORM_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_DATA" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIP_FORM_USER_AUTH
--------------------------------------------------------

  ALTER TABLE "CLIPSOFT"."CLIP_FORM_USER_AUTH" ADD CONSTRAINT "CLIP_FORM_USER_AUTH_PK" PRIMARY KEY ("USER_ID", "FORM_ID", "AUTH_CODE", "PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER"  ENABLE;
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_USER_AUTH" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_USER_AUTH" MODIFY ("FORM_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_USER_AUTH" MODIFY ("AUTH_CODE" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_USER_AUTH" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIP_FORM_USER_GROUP_AUTH
--------------------------------------------------------

  ALTER TABLE "CLIPSOFT"."CLIP_FORM_USER_GROUP_AUTH" ADD CONSTRAINT "CLIP_FORM_USER_GROUP_AUTH_PK" PRIMARY KEY ("USER_GROUP_ID", "FORM_ID", "AUTH_CODE", "PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER"  ENABLE;
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_USER_GROUP_AUTH" MODIFY ("USER_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_USER_GROUP_AUTH" MODIFY ("FORM_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_USER_GROUP_AUTH" MODIFY ("AUTH_CODE" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_FORM_USER_GROUP_AUTH" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIP_MANAGE_ID
--------------------------------------------------------

  ALTER TABLE "CLIPSOFT"."CLIP_MANAGE_ID" ADD CONSTRAINT "CLIP_MANAGE_ID_PK" PRIMARY KEY ("KEY", "PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER"  ENABLE;
  ALTER TABLE "CLIPSOFT"."CLIP_MANAGE_ID" MODIFY ("KEY" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_MANAGE_ID" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_MANAGE_ID" MODIFY ("VALUE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIP_PRODUCT
--------------------------------------------------------

  ALTER TABLE "CLIPSOFT"."CLIP_PRODUCT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_PRODUCT" ADD CONSTRAINT "CLIP_PRODUCT_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIP_USER
--------------------------------------------------------

  ALTER TABLE "CLIPSOFT"."CLIP_USER" ADD CONSTRAINT "CLIP_USER_PK" PRIMARY KEY ("USER_ID", "PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER"  ENABLE;
  ALTER TABLE "CLIPSOFT"."CLIP_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_USER" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIP_USER_GROUP
--------------------------------------------------------

  ALTER TABLE "CLIPSOFT"."CLIP_USER_GROUP" ADD CONSTRAINT "CLIP_USER_GROUP_PK" PRIMARY KEY ("USER_GROUP_ID", "PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER"  ENABLE;
  ALTER TABLE "CLIPSOFT"."CLIP_USER_GROUP" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_USER_GROUP" MODIFY ("USER_GROUP_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIP_USER_GROUP_MAPPING
--------------------------------------------------------

  ALTER TABLE "CLIPSOFT"."CLIP_USER_GROUP_MAPPING" ADD CONSTRAINT "CLIP_USER_GROUP_MAPPING_PK" PRIMARY KEY ("USER_ID", "USER_GROUP_ID", "PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLIP_REPOSITORY_SERVER"  ENABLE;
  ALTER TABLE "CLIPSOFT"."CLIP_USER_GROUP_MAPPING" MODIFY ("USER_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_USER_GROUP_MAPPING" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CLIPSOFT"."CLIP_USER_GROUP_MAPPING" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);


--------------------------------------------------------
--  admin 계정 기초 데이터  pw:clip2018
--------------------------------------------------------
SET DEFINE OFF;
INSERT INTO CLIPSOFT.CLIP_USER (USER_ID,PASSWORD,NAME,USE_YN,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,PRODUCT_ID) VALUES ('admin','$2a$04$4iVUfg9zaTlssUBLZtQ9K.QCTT4VNgn0C50RztDm8JGWM0SATkkWi','관리자','Y',SYSDATE,NULL,SYSDATE,NULL,1)


--------------------------------------------------------
--  e-Form 2.5 PRODUCT 기초 데이터
--------------------------------------------------------
SET DEFINE OFF;
Insert into CLIPSOFT.CLIP_PRODUCT (PRODUCT_ID,PRODUCT_NAME,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID) values (1,'e-Form 2.5
',to_date('18/05/14','RR/MM/DD'),'admin',to_date('18/05/14','RR/MM/DD'),'admin');