
  CREATE TABLE "EFORM"."CLIP_MAPPING_ID" 
   (	"DOCUMENT_KEY" NUMBER, 
	"FORM_ID" NUMBER, 
	"DOCUMENT_CODE" VARCHAR2(20 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER_ID" VARCHAR2(100 BYTE), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_ID" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIP_MAPPING_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EFORM"."CLIP_MAPPING_ID_PK" ON "EFORM"."CLIP_MAPPING_ID" ("DOCUMENT_KEY", "FORM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLIP_MAPPING_ID
--------------------------------------------------------

  ALTER TABLE "EFORM"."CLIP_MAPPING_ID" ADD CONSTRAINT "CLIP_MAPPING_ID_PK" PRIMARY KEY ("DOCUMENT_KEY", "FORM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EFORM"."CLIP_MAPPING_ID" MODIFY ("DOCUMENT_KEY" NOT NULL ENABLE);
 
  ALTER TABLE "EFORM"."CLIP_MAPPING_ID" MODIFY ("FORM_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EFORM"."CLIP_MAPPING_ID" MODIFY ("DOCUMENT_CODE" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table CLIP_NU_FORM_DATA
--------------------------------------------------------

  CREATE TABLE "CLIP_NU_FORM_DATA" 
   (	
   "DATA_RID" NUMBER(12,0), 
	"DATA_IDX" NUMBER(2,0), 
	"FORM_RID" NUMBER(10,0),
	"DATA_XML" BLOB, 
	"COMPLETE_YN" VARCHAR2(1 BYTE), 
	"LAST_YN" VARCHAR2(1 BYTE), 
	"CREATE_DATETIME" VARCHAR2(20 BYTE), 
	"USER_ID" VARCHAR2(14 BYTE), 
	"OCRTAG" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 3 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DATA_XML") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

--------------------------------------------------------
--  DDL for Index PK_CLIP_NU_FORM_DATA
--------------------------------------------------------
  CREATE UNIQUE INDEX "PK_CLIP_NU_FORM_DATA" ON "CLIP_NU_FORM_DATA" ("DATA_RID", "DATA_IDX") 
  PCTFREE 10 INITRANS 5 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------

--  Constraints for Table CLIP_NU_FORM_DATA

--------------------------------------------------------
  ALTER TABLE "CLIP_NU_FORM_DATA" MODIFY ("LAST_YN" NOT NULL ENABLE);
  ALTER TABLE "CLIP_NU_FORM_DATA" MODIFY ("COMPLETE_YN" NOT NULL ENABLE);
  ALTER TABLE "CLIP_NU_FORM_DATA" MODIFY ("DATA_XML" NOT NULL ENABLE);
  ALTER TABLE "CLIP_NU_FORM_DATA" MODIFY ("FORM_RID" NOT NULL ENABLE);
  ALTER TABLE "CLIP_NU_FORM_DATA" MODIFY ("DATA_IDX" NOT NULL ENABLE);
  ALTER TABLE "CLIP_NU_FORM_DATA" MODIFY ("DATA_RID" NOT NULL ENABLE);
  ALTER TABLE "CLIP_NU_FORM_DATA" ADD CONSTRAINT "PK_CLIP_NU_FORM_DATA" PRIMARY KEY ("DATA_RID", "DATA_IDX")
  USING INDEX PCTFREE 10 INITRANS 5 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;




REM INSERTING into EFORM.CLIP_MANAGE_ID
SET DEFINE OFF;
Insert into EFORM.CLIP_MANAGE_ID (KEY,VALUE,CREATE_DATE,CREATE_USER_ID,UPDATE_DATE,UPDATE_USER_ID,PRODUCT_ID) 
values ('DOCUMENT_KEY',1,to_date('18/05/14','RR/MM/DD'),'admin',to_date('18/05/14','RR/MM/DD'),'admin',1);

INSERT INTO EFORM.CLIP_MAPPING_ID ( DOCUMENT_KEY, FORM_ID, DOCUMENT_CODE, CREATE_DATE, CREATE_USER_ID, UPDATE_DATE, UPDATE_USER_ID ) 
VALUES( 1 , 1 , 'A0000001', SYSDATE , 'dpTablo' , SYSDATE , 'dpTablo' );

